### ISSUE TITLE
Create framework for general GUI layout

### ISSUE THREAD

**Issue by wouterjsmit** [ProgrammingLife2016/PL2-2016#1]
The GUI can be fed by real data, or this data can be faked. As long as something appears on the screen that can be interacted with.
- [x] 2 DNA sequences
- [x]  Phylogenetic tree (with current viewport of some sorts)
- [x] Zooming

**Comment by FarisElghlan** [comment]
Phylogenetic tree and zooming are done.

The idea to visualize 2 DNA sequences separately has been dropped, so I will mark this as done and close the topic. Instead we have created a single sequence with multiple paths to visualize the differences. This decision has been made because the data we get already compares the DNA sequences this way and it would be very hard to compare them side by side (which would probably either result in basically the same thing, but harder to read, or something which the user can hardly draw any conclusions from).
If anyone feels like comparing the sequences side by side (in separate views) would actually be a better solution or good in any other way, please open a new ticket with a clear explanation of how this would actually work and what the benefits would be over the currently implemented solution.
