### ISSUE TITLE
GUI must have a minimap whenever not all data is visible

### ISSUE THREAD

**Issue by wouterjsmit** [ProgrammingLife2016/PL2-2016#120]
As soon as some subsets of data disappear from the screen, the user should have a minimap in clear view to let him know where in the data he currently is.

Data can disappear by zooming in, by panning and by querying subsets of the data. An example of the latter is a selection in the phylogenetic tree

**Comment by wouterjsmit** [comment]
Was not able to implement this, because of #127 and more work on #124 .

**Comment by FarisElghlan** [comment]
I don't think this is needed anymore. The current semantic zooming transitions smoothly between zooming levels, so spatial awareness is pretty good already. A nice and pretty easy to implement addition would however be to change the slider of the graph to something like this:
![slider](https://cloud.githubusercontent.com/assets/9753699/15801909/c2f379c4-2aa3-11e6-9d84-4a7919ee1520.png)
Here the 0 and 4,540,903 denote the amount of bases at the start/end position of the slider and the 
1,490,209 - 1,702,231 the range of bases which are currently drawn in the screen.

This would only require the addition of 2 textboxes above the slider (at the start and at the end) and a textbox centered below the slider, which has to be updated according to the current view (this is very easy). This can probably be done within an hour (maybe 2 if it turns out to be harder than expected to layout the textboxes such that as little vertical space is used as possible).

**Comment by wouterjsmit** [comment]
If you manage to squeeze this in, that would be nice, however, it has no priority for this sprint.

**Comment by FarisElghlan** [comment]
Result:
![scrollbar](https://cloud.githubusercontent.com/assets/9753699/15984967/5e9d15f4-2fdd-11e6-9217-0187c469a249.png)
