### ISSUE TITLE
Sequences stored in GraphNode consume a lot of memory

### ISSUE THREAD

**Issue by wouterjsmit** [ProgrammingLife2016/PL2-2016#128]
There could be ways to improve this.
Thoughts are: Do not store the sequences at all or improve the representation to use less bits per base.
- Currently: String where each character is 1 base. (16 bits per character)

Points of thought:
- 5 options, needing 3 bits (with 3^8 - 5 = 3 dead states).
- When mapping the bits into an integer datatype, we still need an array of integers to allow for infinite length sequences. The array brings some overhead and should be minimized.
- The dead states can be used when doing bit shifts to mark the end of the sequence (let 000 mark the end).

**Comment by FarisElghlan** [comment]
I was actually incorrect: shorts are not the same size in memory as integers. The Byte, Short and Integer Objects all are the same size however (each of them is 16 bytes), because an Object must always have a size which is a multiple of 8 bytes (the leftover bytes are not used) and an Object has a default size of 12 (?).

Since arrays are objects and objects always have a size divideable by 8 (and a base size of 12) however, there is no difference between using a byte array and int array for this purpose. The only difference is that computations on integers are a little bit faster than computations on bytes.

After running some calculations taking into account everything which is described above I got to the following reduction in memory usage:
Using int arrays: 18 744 968 bytes
Using Strings: 96 781 400 bytes (this is not calculated, but based on running the code)

So this would be a memory reduction of around 80%
