### ISSUE TITLE
Annotation jump is inaccurate

### ISSUE THREAD

**Issue by wouterjsmit** [ProgrammingLife2016/PL2-2016#272]

**Comment by FarisElghlan** [comment]
annotation jump is accurate?

**Comment by wouterjsmit** [comment]
Nvm, Cas mentioned this, but it is sorta fine. Sometimes it is a little weird, also for `DS6 9546 bp` gene I don't seem to find anything (the jump jumps to a long edge, but I cannot find the gene.

**Comment by FarisElghlan** [comment]
That's caused by the reference genome not actually being drawn in the graph, since it is not present in the tree. The node which is jumped to simply doesn't exist in the drawn graph. The location which you jump to in this case is the position of the node which has the annotation, but it isn't drawn so you can't see the annotation

**Comment by wouterjsmit** [comment]
Right, that explains.
