### ISSUE TITLE
PMD makes the build failing

### ISSUE THREAD

**Issue by cbilstra** [ProgrammingLife2016/PL2-2016#58]
The build on the test/model branch failes because of PMD, because travis says there are 3 PMD errors. First of all, there are much more of them when I look at my local maven site report. But almost all of them are a 2-character variable violation. (which is thus not in compliance with our checkstyle), and I think travis does not fail because of that. @FarisElghlan, there are also some violations in your annotations code, maybe we should also fix those? I hope somebody can find the reason why travis fails and I think we should remove the variable rule from PMD.

**Comment by FarisElghlan** [comment]
No idea what the errors in the maven site are based on  @Pathemeous ???, but you only have to fix the 3 errors which are given when the build completes. In your case the file path is: `PL2-2016\PL2\PL2-parser\target\pmd.xml` (this file path is given at the end of the build). It contains the following stuff:

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<pmd version="5.3.5" timestamp="2016-05-09T18:14:58.740">
<file name="...\PL2-2016\PL2\PL2-shared\src\main\java\interfaces\DataAlgoInterface.java">
<violation beginline="14" endline="14" begincolumn="10" endcolumn="30" rule="UnusedModifier" ruleset="Unused Code" package="interfaces" class="DataAlgoInterface" method="getNode" externalInfoUrl="https://pmd.github.io/pmd-5.3.5/pmd-java/rules/java/unusedcode.html#UnusedModifier" priority="3">
Avoid modifiers which are implied by the context
</violation>
<violation beginline="21" endline="21" begincolumn="10" endcolumn="45" rule="UnusedModifier" ruleset="Unused Code" package="interfaces" class="DataAlgoInterface" method="getPhylo" externalInfoUrl="https://pmd.github.io/pmd-5.3.5/pmd-java/rules/java/unusedcode.html#UnusedModifier" priority="3">
Avoid modifiers which are implied by the context
</violation>
<violation beginline="28" endline="28" begincolumn="10" endcolumn="35" rule="UnusedModifier" ruleset="Unused Code" package="interfaces" class="DataAlgoInterface" method="getMeta" externalInfoUrl="https://pmd.github.io/pmd-5.3.5/pmd-java/rules/java/unusedcode.html#UnusedModifier" priority="3">
Avoid modifiers which are implied by the context
</violation>
</file>
</pmd>
```

Whichs means that you should not use the `public` identifier for methods in the interface `...\PL2-2016\PL2\PL2-shared\src\main\java\interfaces\DataAlgoInterface.java`, since methods in interfaces are `public` by default (so just leave out the `public` keyword).

**Comment by cbilstra** [comment]
Thanks, I will try that.

**Comment by wouterjsmit** [comment]
@FarisElghlan @cbilstra I noticed that PMD somehow reports more warnings/errors than it finds during the build. See #62.

**Comment by wouterjsmit** [comment]
Since the annotation code from Faris does not fail the build, fixing it is not a priority and will be completely up to @FarisElghlan. Potentially we should consider excluding it from the static analysis completely, since it is not part of our project.

While working on #62, I will make sure to synchronize the Checkstyle and PMD.

You may close this if this solves the issue @cbilstra

**Comment by cbilstra** [comment]
@FarisElghlan @Pathemeous thanks for the help, I fixed it. Build for test/model finally succeeds on travis now, checkstyle apparently started complaining about some lines in the annotation code.
